# Generated by Django 6.0.2 on 2026-03-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_date', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('disposition', models.CharField(max_length=100)),
                ('last_dial_outcome', models.CharField(blank=True, max_length=255)),
                ('recording_url', models.URLField(blank=True, max_length=500, null=True)),
                ('attempt_count', models.IntegerField(default=1)),
                ('powerlist_id', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('company_domain', models.CharField(blank=True, max_length=255)),
                ('linkedin_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-call_date'],
            },
        ),
    ]
