# Generated by Django 6.0.2 on 2026-03-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callreport',
            name='note',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
