# Generated by Django 6.0.2 on 2026-03-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_callreport_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='callreport',
            name='powerlist_notes',
            field=models.CharField(blank=True, max_length=1500),
        ),
    ]
