# Generated by Django 6.0.2 on 2026-04-23 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_callreport_powerlist_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='callreport',
            name='ss_data_raw',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
