# Generated by Django 6.0.2 on 2026-09-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customer_customerpowerlist_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DialAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=100, unique=True)),
                ('call_date', models.DateTimeField()),
                ('call_type', models.CharField(blank=True, max_length=20)),
                ('powerlist_id', models.IntegerField(blank=True, null=True)),
                ('from_number', models.CharField(blank=True, max_length=20)),
                ('to_number', models.CharField(blank=True, max_length=20)),
                ('agent_name', models.CharField(blank=True, max_length=200)),
                ('agent_email', models.EmailField(blank=True, max_length=254)),
                ('agent_user_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-call_date'],
            },
        ),
    ]
